all : ChangeCase CheckFileStatus CheckIfFileExists CompareFiles CountLines CountUniqueWordsInFile \
	CountWordsAndChars Decrypt DecryptFile Encrypt EncryptFile FindWordInFile ListFiles \
	ListFilesRecursively RemoveWordFromFile ReplaceStringInFile TreeFilesLList DoubleLinkedList
DoubleLinkedList : DoubleLinkedList.c
	gcc DoubleLinkedList.c -Wall -pedantic -ansi -o DoubleLinkedList
ChangeCase : ChangeCase.c 
	gcc ChangeCase.c -Wall -pedantic -ansi -o ChangeCase 
CheckFileStatus : CheckFileStatus.c 
	gcc CheckFileStatus.c -Wall -pedantic -ansi -o CheckFileStatus 
CheckIfFileExists : CheckIfFileExists.c 
	gcc CheckIfFileExists.c -Wall -pedantic -ansi -o CheckIfFileExists 
CompareFiles : CompareFiles.c 
	gcc CompareFiles.c -Wall -pedantic -ansi -o CompareFiles 
CountLines : CountLines.c 
	gcc CountLines.c -Wall -pedantic -ansi -o CountLines 
CountUniqueWordsInFile : CountUniqueWordsInFile.c 
	gcc CountUniqueWordsInFile.c -Wall -pedantic -ansi -o CountUniqueWordsInFile 
CountWordsAndChars : CountWordsAndChars.c 
	gcc CountWordsAndChars.c -Wall -pedantic -ansi -o CountWordsAndChars 
Decrypt : Decrypt.c 
	gcc Decrypt.c -Wall -pedantic -ansi -o Decrypt 
Encrypt : Encrypt.c 
	gcc Encrypt.c -Wall -pedantic -ansi -o Encrypt 
DecryptFile : DecryptFile.c 
	gcc DecryptFile.c -Wall -pedantic -ansi -o DecryptFile 
EncryptFile : EncryptFile.c 
	gcc EncryptFile.c -Wall -pedantic -ansi -o EncryptFile 
FindWordInFile : FindWordInFile.c 
	gcc FindWordInFile.c -Wall -pedantic -ansi -o FindWordInFile 
ListFiles : ListFiles.c 
	gcc ListFiles.c -Wall -pedantic -ansi -o ListFiles 
ListFilesRecursively : ListFilesRecursively.c 
	gcc ListFilesRecursively.c -Wall -pedantic -ansi -o ListFilesRecursively 
RemoveWordFromFile : RemoveWordFromFile.c 
	gcc RemoveWordFromFile.c -Wall -pedantic -ansi -o RemoveWordFromFile 
ReplaceStringInFile : ReplaceStringInFile.c 
	gcc ReplaceStringInFile.c -Wall -pedantic -ansi -o ReplaceStringInFile 
TreeFilesLList: TreeFilesLList.c
	gcc TreeFilesLList.c -Wall -pedantic -ansi -o TreeFilesLList
